language: python

python: 3.6

install:
- pip install -r requirements/dev.txt
- pip install codecov

script:
- python -m unittest discover
- coverage erase
- coverage run --source=ChangePop test_webapp.py
- ls
- coverage html

after_success:
- codecov

branches:
  only:
  - master
  - develop
  
deploy:
  matrix:
  - provider: heroku
    api_key:
      secure: GxXEHkHqdAAO7GiLsHyESxT3HseZeZJiOn/KiqBjekfmz2KxXmupGPSvyl+m21awJup8xBq2133b99Ih0uwMs2UGeos4WlSGFJzYwZegkdzIpjsS9m/75ZtK3wQqfnj1ssPZDUNzjIzHpcL3SOwWOcNTNVcdN+DiymtdskrxYezDIhCW7MdjSaA6XNdrIKntlPUkwYF34HEKKy2W48qT4IqSmi1HgDhcgDjUqbsOZVnSfM02fMO3fBUDACqXYuRgbHvcLDhPzmp0oMgHZI6BYam7WBuLjjhLmPu5guxCkMdfupo2mga6C2hWggJ5DEixPqE/1EUFlXs00knsvo7z7MwNv5hSD6YlbbaU/idf+ZXT2UgJooF/k01k1ZVM2sdQfF2q9mwn/q9eqqaofclvZHHE/2V29RIzPyOfh/HYbCt+0kiFa8w9Z5EozMRdhjjME5W+lJlIYBrnMBZLqcnbHUvQ4oN3Br12qUsuk0Mqtt5YtWhoxxfjmItFygeEctDHzLIC9Rh+UhHsYS7x+Ebp978OkUxDF40XZE2i3OCYMRxQm3YNWjRbU55p/RRhrF7J8chPVHVTkoWqQCmQ9bpErxn5+VyE37HdTFix0ySSax2iTHBaW8/1o1ykttwAtoX0wZdTDEfiKlVn1ReXZqpDnG/nUWTA7ZSfK3emC24Fz3I=
    app: changepop-fw
    on:
      python: 3.6
      branch: master
    