language: python
python: 3.6
install:
- pip install -r requirements/dev.txt
- pip install codecov
script:
- python -m unittest discover
- coverage erase
after_success:
- codecov
branches:
  only:
  - master
deploy:
  - provider: heroku
    api_key:
        secure: uQENf2OyKKUJrGx03b+k6Gg8iWX8zNsU4HGTtDe/Ic75pUWSm0k0o8MGoSaU1HY51GUsYCdXC+Nys1HNZivqI9qr4D6rZi6FG39QpEVWCXlmhCUjSPd0zLOLkfyNapP+/Uz4kxeXRY8ggMkxGqGcdGuJf1bR9wqC4MfRllcUqIGLAWKhbxN3vz5EnFi4oh+Le92osDFoJf0SyW0AtsuwzxT+EBPYG5olyWz7U7Mt9G3JUSSVpceB0RYo8beXTE/ekkkq+ZxoHmy9hztnbF+C9LqAmCYzcozHqLCN+P+qCz1Dwvyvy3USgVNne8sFx9mK/T8PVwukLsClBzY4C22QDDWynEnVty/hqoK5I23uGrGlJIKHPKLCT2alReq+kQp1ds9lUvL/q8R7H4iDLBL99E+l6fojtWKQ9o8y8n8V1YPkLMYYzxT3R85pKZApQ/BqgQZbnaCKeCX1TQGkMYz8UH5XpJ5NMW3CHmZ5VTxl+SfQyglIEIKvs9E2nGvtjvtyoUZNz7u1uJMARPkT1pCUCtJvsvR1SfZs1JxxGrc4Si9vJJutoykHMpGT+1xM5nFTwi9umLE+FX01I0ADyWNs5h7S4vHRaMBBlbJS9Emd1QX2EKhqI6GWljDZ7v7k/9dPEeVrEtEYVO+xoXaQNJm0hQ9veGtRQU/GX9xvbVxr6a4=
    app: changepop-fw
    on:
        python: 3.6