language: python

python: 3.6

install:
- pip install -r requirements/dev.txt
- pip install codecov

script:
- python -m unittest discover
- coverage erase
- coverage run test_webapp.py
- ls
- coverage html

after_success:
- codecov

branches:
  only:
  - master
  - develop
  
deploy:
  - provider: heroku
    api_key:
        secure: h8xt0EpLEu67fxIzC/IKDpZHvkEY5whtNZdgcs118MhWK52oUj0oKK50ur9xel9m5GeDc7McQ9I06MemPB9cqgIFj7eQFqgjiVIN4rHvsJsY3hYO1hxorfQIy50yE3rsz0TxJrMZVibnOx9Q1Vu2xULw7+PTNsN5Kq2Fdge8R5UiSibCg/Fz1IVpLXv18SSwa6vgwaU0mqp6CszD0xaB1iSjuFDZGw3TSuXFkiQm9dTviXsT4St7uyYJCHweE58zZLB1rFL54uuV+d8DQlggTunpXT/xWERFcO75YddHWdauXAsio9DQRdm7GfFcVeHkNgUoZ/5oGlkBbOQ/iI2FXhyoCk5GvbFVibD4CTvFM2vHOxmGUN5slW1cXbRVJjyUtPiaQ0Bc5H/IkeaYEFuFRzEU72xo53DUvjt9PuKDHhoz7pBak4Xi9Bh+oA4l1IAzrvG2ZjaOjbFSvxpcc8mL75Dt13i1+E4PPTvcgsLYqLUpP5KTDExTYzrAWgrDlQyS9ZDLBwA9rKUbhP67CA9ViiOMXM7+i7iXk7S1Xjsfff4qca9AwdEHyqgPb8Pdw5HKOqmZyf1CQx1IJjhemlNOtMsKTPMgxfV63VvbMNnVe2iFp2h3WQFuMBSyF5YOGdCbDdvoQHZ4peGVCj0EW+eg4fr/IjmjGwTMi2vJU08nQLY=
    app: changepop-fw
    on:
      python: 3.6
      branch: master
